# Generated by Django 3.2.12 on 2022-06-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_personaldetials_organizationldetials'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('org_name', models.CharField(max_length=100, verbose_name='Organization Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='organizationldetials',
            options={'verbose_name_plural': 'Organizations'},
        ),
    ]
