# Generated by Django 3.2.12 on 2022-06-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220619_1846'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationName',
        ),
    ]
