# Generated by Django 3.2.12 on 2022-07-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_organizationldetials_org_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationldetials',
            name='account_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Account No'),
        ),
        migrations.AddField(
            model_name='organizationldetials',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='organizationldetials',
            name='branch_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Branch Name'),
        ),
        migrations.AddField(
            model_name='organizationldetials',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IFSC Code'),
        ),
        migrations.AddField(
            model_name='organizationldetials',
            name='upi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='UPI No'),
        ),
    ]
